# Generated by Django 5.2.7 on 2025-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-Subscribed_at'],
            },
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='QueryRelated',
            field=models.CharField(choices=[('', 'Query Related'), ('general', 'General Inquiry'), ('support', 'Support'), ('feedback', 'Feedback')], max_length=50),
        ),
    ]
