# Generated by Django 5.2.8 on 2025-11-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subscriber_alter_contactmessage_queryrelated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='Subscribed_at',
            new_name='subscribed_at',
        ),
    ]
